version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_sas
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sas
    volumes:
      - pgdata:/data/postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sas_api
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
      - /usr/src/app/node_modules
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local